### ISSUE TITLE
Add Bug bounty village in owaspseaside website under sessions

### ISSUE THREAD

**Issue by proxy-test** [owaspseasides/2020#11]
After adding bug bounty village in sessions, redirect it to https://bugbountyvillage.com

Also, please use the attached bug bounty logo image for the same.

![Bug bounty6 (1)](https://user-images.githubusercontent.com/22179154/72964495-11debc80-3de0-11ea-988d-092ff745e1ec.jpg)

**Comment by parag85** [comment]
Added.
